name: 'QA checks'

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-api:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    defaults:
      run:
        working-directory: ./backend/SqliteRemoteApi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./backend/SqliteRemoteApi/global.json
      - name: Cache NuGet
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore project
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: Prepare SSH configuration
        run: |
          mkdir -m 700 -p ~/.ssh/
          
          npm ci
          npm run gen:ssh-config
          cp generate-ssh-config/config.gen ~/.ssh/config
          
          chmod 600 ~/.ssh/config
        working-directory: ./ci/scripts
      - name: Generate SSH key
        run: |
          ssh-keygen -f ~/.ssh/id_sqlite_remote -t ed25519 -N ""
          chmod 600 ~/.ssh/id_sqlite_remote
          chmod 644 ~/.ssh/id_sqlite_remote.pub
      - name: Launch mock servers
        run: docker compose up -d
        working-directory: ./mock-server
      - name: Run tests
        run: dotnet test --no-restore --no-build
      - name: Stop mock servers
        run: docker compose down
        working-directory: ./mock-server
        if: always()

  check-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file:  ./frontend/.nvmrc
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run style
      - run: npm run ts
      - run: npm run build

  check-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @action-validator/core @action-validator/cli --save-dev
      - run: find .github/workflows/qa-checks.yml | xargs -I {} npx action-validator {}
